gems:
  - jekyll-redirect-from
timezone: America/Los_Angeles
permalink: /:title/
paginate: 40
paginate_path: articles/page:num/
markdown: kramdown
url: https://cdavidmaxey.com
cache: https://cda.vidmaxey.com
video: https://d21zrsmzxdylmx.cloudfront.net
email: "info@CDavidMaxey.com"
telephone: "503-928-4182"
tel: "+1-503-928-4182"
facsimile: "503-926-6433"
fax: "+1-503-926-6433"
Person:
  name: C. David Maxey
  givenName: David
  familyName: Maxey
  honorificSuffix: M.A.
  additionalName: Charles David Maxey
  jobTitle: Licensed Psychologist Associate
  naics: 621330
  disambiguatingDescription: "C. David Maxeyâ€™s full name is Charles David Maxey, and he goes by David. Maxey is sometimes misspelled Maxcy, Maxi, Maxcey, Macksey, Maxe, or Maxie."
  image: "CDavidMaxey.jpg"
  addressLocality: Portland
  addressRegion: OR
  postalCode: 97223
  streetAddress: "6950 SW Hampton St Suite 207"
Publisher:
  name: CDavidMaxey.com
  logo:
    src: "wordmark.png"
    X: 333
    Y: 60
feedTitle: "C. David Maxey, M.A."
mail:
  address: "6950 SW Hampton St Suite 207"
  city_state: "Portland, OR"
  zip: "97223"
office:
  address: "6950 SW Hampton St Suite 207"
  address_formatted: "<div>6950 SW Hampton St&nbsp;</div><div>Suite 207</div>"
  city_state: "Portland, OR"
  zip: "97223"
applemaps:
  url: "https://maps.apple.com/?q=C.+David+Maxey,+M.A.,+Licensed+Psychologist+Associate"
  documentation: "https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html"
googlemaps:
  url: "https://g.page/cdavidmaxey"
  url_full: "https://www.google.com/maps/search/?api=1&query=C.+David+Maxey,+M.A.,+Licensed+Psychologist+Associate"
  documentation_url: "https://developers.google.com/maps/documentation/urls/guide"
  documentation_place_id: "https://developers.google.com/places/place-id"
  api: "https://maps.googleapis.com/maps/api/staticmap"
  parameters: "?zoom=15&size=640x640&scale=2&markers=scale:2|icon:https://cdavidmaxey.com/map-pin.png?v=3|6950+SW+Hampton+St+Suite+207,Portland,OR&key=AIzaSyDCxo9x_qGwB3DbswOdJaEqbsMxEcalTgA"
  signature: "&signature=yWWy00OOGww_gz3PW_nyAXfN_oI="
  api_console: "https://console.developers.google.com/google/maps-apis/api-list"
  documentation_maps_static: "https://developers.google.com/maps/documentation/maps-static/intro"
collections:
  timer:
    output: TRUE
    permalink: "/:name"
alert-none: "<strong>Accepting New Clients:</strong> Complete an online <strong><a href='https://cdavidmaxey.com/#new' rel='nofollow'>New&nbsp;Client&nbsp;Request</a></strong>&nbsp;form.<br>Services are provided in-office or by video call, as appropriate."
gold-alert: TRUE